# Generated by Django 4.2.5 on 2023-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_student_number_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('past', 'Past Due')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('current', 'Current Student'), ('past', 'Past Student'), ('sick', 'Sick Student')], max_length=10),
        ),
    ]
