# Generated by Django 4.2.5 on 2023-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_fee_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first_aid', 'First Aid'), ('cpr', 'CPR'), ('6m_criminal_record', '6m Criminal Record'), ('1yr_criminal_record', '1yr Criminal Record')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_first_name', models.CharField(max_length=50)),
                ('staff_last_name', models.CharField(max_length=50)),
                ('staff_birth_date', models.DateField()),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_phone', models.CharField(max_length=15)),
                ('certificates', models.ManyToManyField(blank=True, to='students.certification')),
            ],
        ),
    ]
